# Generated by Django 4.0.2 on 2022-02-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Masteranswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course', models.CharField(choices=[('CS', 'CS'), ('EC', 'EC')], default='CS', max_length=200)),
                ('Ques', models.IntegerField()),
                ('Type', models.CharField(choices=[('NAT', 'NAT'), ('MCQ', 'MCQ'), ('MSQ', 'MSQ')], default='MCQ', max_length=200)),
                ('Ans_opt', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('AB', 'AB'), ('AC', 'AC'), ('AD', 'AD'), ('BC', 'BC'), ('BD', 'BD'), ('CD', 'CD'), ('ABC', 'ABC'), ('ABD', 'ABD'), ('ACD', 'ACD'), ('BCD', 'BCD'), ('ABCD', 'ABCD')], default='A', max_length=200)),
                ('Ans_natl', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('Ans_nath', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('corr_mark', models.DecimalField(decimal_places=2, default=2, max_digits=5)),
                ('neg_mark', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('mta', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Response_sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Link', models.TextField()),
            ],
        ),
    ]
